# Java Maven CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/openjdk:8-jdk

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/postgres:9.4

    working_directory: ~/repo

    environment:
      # Customize the JVM maximum heap limit
      MAVEN_OPTS: -Xmx3200m
      PROD_BRANCH: master
      
    steps:
      - add_ssh_keys:
          fingerprints:
            - "84:06:12:9b:96:d1:dd:7a:7b:42:7c:21:17:6e:f8:c2"
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "pom.xml" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: mvn dependency:go-offline

      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "pom.xml" }}

      # run tests!
      - run: echo "${MAVEN_OPTS}"
      
      - store_artifacts:
          path: /home/circleci/repo/target/dataturks-1.0-SNAPSHOT.war
workflows:
  version: 2
  build-approve-deploy:
    jobs:
      - build: 
         filters:
           branches:
             only:
              - master 
