--- 
jobs: 
  build: 
    environment: 
      DEPLOY_BRANCH: master
      DEPLOY_ENV: stage
    machine: true
    steps: 
      - 
        checkout: ~
      - 
        store_artifacts: 
          path: ~/repo/docker
    working_directory: ~/repo
  build_deploy: 
    environment: 
      CIRCLE_TOK: 9d5ba374d07f1c3ca55563cf5c74c38b45843ad4
      DEPLOY_BRANCH: master
      DEPLOY_ENV: stage
    machine: true
    steps: 
      - 
        run: 
          command: |
              curl https://circleci.com/api/v1.1/project/github/${CIRCLE_PROJECT_USERNAME}/${CIRCLE_PROJECT_REPONAME}/${CIRCLE_BUILD_NUM}/latest/artifacts?circle-token=${CIRCLE_TOK}
              ls /home/circleci
          name: "Restore Artifacts"
    working_directory: ~/repo
workflows: 
  build-approve-deploy: 
    jobs: 
      - 
        build: 
          filters: 
            branches: 
              only: 
                - master
      - 
        build_deploy: 
          filters: 
            branches: 
              only: master
          requires: 
            - build
  version: 2
