# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2

jobs:
  build:
    #docker:
    machine: true
      # specify the version you desire here
      #- image: circleci/node:10

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mongo:3.4.4

    #resource_class: large
    working_directory: ~/repo
    
    environment:
      DEPLOY_BRANCH: master
      DEPLOY_ENV: stage # The Values for this parameter will stage / uat / prod. No other values are allowed

    steps:
      - checkout:
          
      - store_artifacts:
          path: ~/repo/docker
          
  build_deploy:  
    
    machine: true    
    working_directory: ~/repo # directory where steps will run
    environment:
      DEPLOY_BRANCH: master
      DEPLOY_ENV: stage # The Values for this parameter will stage / uat / prod. No other values are allowed
      CIRCLE_TOK:
      
    steps:
     
      - run:
          name: Restore Artifacts
          command: |
             curl https://circleci.com/api/v1.1/project/github/${CIRCLE_PROJECT_USERNAME}/${CIRCLE_PROJECT_REPONAME}/latest/artifacts?circle-token=${CIRCLE_TOK}           
     
