--- 
jobs: 
  build: 
    environment: 
      DEPLOY_BRANCH: master
      DEPLOY_ENV: stage
    machine: true
    steps: 
      - run:
          command: |
           mkdir -p /tmp/core_dumps
           cd /tmp/core_dumps
           touch test.txt
           echo "Hello World" > test.txt
      - 
        store_artifacts: 
          path: /tmp/core_dumps
    working_directory: ~/repo
  build_deploy: 
    environment: 
      CIRCLE_TOK: ee79fb4cf1a60a98243d3324c088197aba8839a5
      DEPLOY_BRANCH: master
      DEPLOY_ENV: stage
    machine: true
    steps: 
      - 
        add_ssh_keys: 
          fingerprints: 
            - "9d:ce:5b:0e:1a:bb:8e:62:24:72:c7:0d:f4:1e:6c:21"
      - 
        run: 
          command: |
              echo ${CIRCLE_PROJECT_USERNAME};
              echo ${CIRCLE_PROJECT_REPONAME};
              echo ${CIRCLE_BUILD_NUM};
              echo ${CIRCLE_TOK};
              curl https://circleci.com/api/v1.1/project/github/${CIRCLE_PROJECT_USERNAME}/${CIRCLE_PROJECT_REPONAME}/${CIRCLE_BUILD_NUM}/artifacts?circle-token=${CIRCLE_TOK};
              ls /home/circleci/repo;
          name: "Restore Artifacts"
    working_directory: ~/repo
workflows: 
  build-approve-deploy: 
    jobs: 
      - 
        build: 
          filters: 
            branches: 
              only: 
                - master
      - 
        build_deploy: 
          filters: 
            branches: 
              only: master
          requires: 
            - build
  version: 2
